language: ruby
sudo: false
rvm:
  - 1.9
  - 2.1
  - 2.2.2
script: bundle exec jekyll build && htmlproof ./_site
install: bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer