language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.2
install: bundle install
script: bundle exec rake site:deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- echo -e "Host peacock.uberspace.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_7aef735ff37c_key -iv $encrypted_7aef735ff37c_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa