# Site settings
name: The Uberblock
author:
  name: "Christian Vervoorts"
  email: mail@uberblock.de
  twitter: sangyye
about_me: "System-Administrator with a penchant for FreeBSD"
description: "Uberblock is a little blog, about programming, servers and unix. I will review some things, write some HowTos and make a caffeine injected rant or two."
baseurl: ""
url: "https://uberblock.de"
twitter_username:  sangyye
github_username:   sangyye
tumblr_username:   sangyye

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

exclude: [README.md, Gemfile, Rakefile, deploy_key.enc, deploy_key]

jekyll-archives:
  layouts:
    year: archive-year
    month: archive-month
  enabled:                         
    - year
    - month

# Rake settings
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

# seo-jekyll-tag
twitter:
  username: sangyye

# Add plugins
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
